version: "3.8"
services:
  redis:
    image: redis:7-alpine

  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - redis
    volumes:
      - ./channels.json:/app/channels.json
      - ./avatars.json:/app/avatars.json
      - ./static/uploads:/app/static/uploads
      - ./static/avatars:/app/static/avatars
    environment:
      - FLASK_SECRET=change_me
      - FLASK_ENV=production
      - SECRET_KEY=change-me
      - MESSAGE_QUEUE=redis://redis:6379/0
      - CHANNELS_FILE=/app/channels.json
      - AVATARS_FILE=/app/avatars.json
      - UPLOAD_FOLDER=/app/static/uploads
    restart: unless-stopped
    command: python app.py
